config/routes.rb
Didact::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :ols, :path => '/o', :except=>:destroy
  
  match 'o/:id/learn/:page' => 'ols#quiz', :via => :put
  match 'o/:id/learn/:page' => 'ols#learn', :via => :get
  match 'o/:id/testall' => 'ols#testall', :via => :get
  match 'o/:id/quizall' => 'ols#quizall', :via => :put
  match 'o/:id/improve' => 'ols#improve', :via => :get
  match 'o/:id/revise' => 'ols#revise', :via => :get
  match 'o/:id/quizimprove' => 'ols#quizimprove', :via => :put

  resources :uls, :path => '/u', :except=>:destroy
    
  match 'u/:id/learn/:page' => 'uls#quiz', :via => :put
  match 'u/:id/learn/:page' => 'uls#learn', :via => :get
  match 'u/:id/testall' => 'uls#testall', :via => :get
  match 'u/:id/quizall' => 'uls#quizall', :via => :put
  match 'u/:id/improve' => 'uls#improve', :via => :get
  match 'u/:id/revise' => 'uls#revise', :via => :get
  match 'u/:id/quizimprove' => 'uls#quizimprove', :via => :put
  
  resources :t2ts, :path => '/tt', :except=>:destroy
    
  match 'tt/:id/learn/:page' => 't2ts#quiz', :via => :put
  match 'tt/:id/learn/:page' => 't2ts#learn', :via => :get
  match 'tt/:id/testall' => 't2ts#testall', :via => :get
  match 'tt/:id/quizall' => 't2ts#quizall', :via => :put
  match 'tt/:id/improve' => 't2ts#improve', :via => :get
  match 'tt/:id/revise' => 't2ts#revise', :via => :get
  match 'tt/:id/quizimprove' => 't2ts#quizimprove', :via => :put
  
  resources :i2ts, :path => '/it', :except=>:destroy
    
  match 'it/:id/learn/:page' => 'i2ts#quiz', :via => :put
  match 'it/:id/learn/:page' => 'i2ts#learn', :via => :get
  match 'it/:id/testall' => 'i2ts#testall', :via => :get
  match 'it/:id/quizall' => 'i2ts#quizall', :via => :put
  match 'it/:id/improve' => 'i2ts#improve', :via => :get
  match 'it/:id/revise' => 'i2ts#revise', :via => :get
  match 'it/:id/quizimprove' => 'i2ts#quizimprove', :via => :put
  
  root :to => 'home#index'
  

end

app/models/ul.rb
require 'quiz'

class Ul < Quiz
  validates_presence_of :items
  validates_length_of :items, :within => 2..1000
    
  private
  field :items, :type => Array  
  
  public
  def mark (attempt)
    right = Array.new
    wrong = Array.new

    if !!attempt
      items_copy = Array.new(items)
      
      attempt.values.each do |value|
        value.strip!
        
        next if value.length == 0
        
        index = nil
        
        items_copy.each_index do |ind| 
          if soft_equal(value, items_copy[ind])
            index = ind
            break
          end
        end
        
        if index
          right.push value.to_s[0..200]
          items_copy.delete_at(index)
        else
          wrong.push value.to_s[0..200]
        end

      end
    end
    
    {right: right, wrong: wrong}
  end
  
  def get_data(min_value, max_value)
    return items[min_value,1 + max_value - min_value].shuffle;
  end
end

app/controllers/uls_controller.rb
class UlsController < QuizController
  def initialize
    super('Ul')
  end
  
  def item_update(item, updateParams)
    if(not updateParams[:ul].nil?)
      item.update_attributes(updateParams[:ul])
      
      if(not updateParams[:ul][:items].nil?)      
        vals = updateParams[:ul][:items].to_s.lines.to_a
        vals.each { |x| x.strip! }
        vals.delete_if { |val| val.length == 0 }
        
        item.items = vals
      end
    end
  end
  
  def get_improvement_data
    last_try = current_user.get_last_imperfect_go(@item)
   
    if last_try.right.length == @item.items.length
      then @item.get_all_data
    else
      @item.items.select{|value| not last_try.right.include?(value)}
    end
  end
end

app/views/uls/_display_list.erb
<% if not @data.nil? %>
  <ul>
    <% @data.each do |value| %>
      <li><%=value%></li>
    <%end%>
  </ul>
<%end%>

app/views/uls/_edit_form.erb
<%= form_for(@item) do |f| %>
  <% if (not @item.errors.nil?) and @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> stopped us saving:</h2>

      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, 'Name:' %>
  <%= f.text_field :name %>

  <br/>
  <br/>
  Items:<br/>
  <% initialValue = if @data.nil? or @data.length == 0 then "Item 1\nItem 2\nItem 3" else @data.join("\n") end%>
  <%= f.text_area :items, :size => '30x10', :value=> initialValue%>

  <div class="actions">
    <%= f.submit 'Update!', class: "btn"%>
  </div>
<% end %>

app/views/uls/_results_display.erb
<%if not @right.nil? and not @right.empty?%>
  You <span style="color:#080; font-weight:bold;">aced</span> these:
  <ul>
    <% @right.each do |value| %>
      <li><%= value %></li>
    <%end%>
  </ul>
<%end%>

<% if not @missed.nil? and not @missed.empty? %>
  You <span style="color:#800; font-weight:bold;">forgot</span> these:
  <ul>
    <% @missed.each do |value| %>
      <li><%= value %></li>
    <%end%>
  </ul>
<%end%>

<%if not @extra.nil? and not @extra.empty?%>
  These were <span style="color:#800; font-weight:bold;">wrong</span>:
  <ul>
    <% @extra.each do |value| %>
      <li><%=value%></li>
    <%end%>
  </ul>
<%end%>

app/views/uls/display.html.erb
<h3>OK, now learn these <%=@item.name%>:</h3>

<%= render 'display_list' %>

<%= link_to 'Test me!', @test_url%>

<br/>
<br/>

<%= link_to 'Back to menu', :root %>

app/views/uls/edit.html.erb
<h3>Editing <%=@item.name%></h3>

<%= render 'edit_form' %>

<%= link_to 'Show ' + @item.name, @item %>
<br/>
<br/>
<%= link_to 'Back to menu', :root %>

app/views/uls/full_results.html.erb
<%
@right = @results[:right].select { |key,value| not @data.index(key).nil? }
@extra = @results[:wrong].select { |key,value| @data.index(key).nil? }
@missed = @data.select{|item| @results[:right].index(item).nil?}
%>

<h3><%=@right.length%> out of <%=@data.length%>:</h3>

<%= render 'results_display' %>

<%= link_to 'Try again', url_for(:action => :testall) %>
| 
<%= link_to 'Back to ' + @item.name, url_for(:action => :show) %>
<br/>
<br/>
<%= link_to 'Back to menu', :root %>

app/views/uls/improve_results.html.erb
<%
@right = @results[:right].select { |value| @data.include?(value) }
@missed = @data.select { |value| not @results[:right].include?(value) }
%>

<h3><%=@right.length%> out of <%=@right.length + @missed.length%>:</h3>

<%= render "results_display" %>

<%= link_to 'Try again', url_for(:action => :improve) %> |
<%= link_to 'Back to ' + @item.name, url_for(:action => :show) %>

<br/>
<br/>
<%= link_to 'Back to menu', :root %>

app/views/uls/index.html.erb
<h3>All available unordered Pogos</h3>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @items.each do |ul| %>
    <tr>
      <td><span style="font-size:2em"><%=ul.name%></span> <br/>
        <%= link_to 'Show', ul %>
        | <%= link_to 'Learn all', url_for(:action => 'learn', :id => ul, :page => 0) %>
        | <%= link_to 'Quiz all', url_for(:action=>'testall', :id => ul) %>
        | <%= link_or_text(has_history?(ul), 'Revise', url_for(:action=>'revise', :id=>ul), 'Log in to revise pogos you\'ve tried before') %>
        <% if can_edit?(ul) %>
          | <%= link_to 'Edit', edit_ul_path(ul) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<br />

<%= link_or_text(can_create?, 'Create new unordered Pogo', new_ul_path, 'Log in to create pogos') %>

app/views/uls/new.html.erb
<h3>New unordered Pogo</h3>

<%= render 'edit_form' %>

<%= link_to 'Back', :root %>

app/views/uls/show.html.erb
<h3><%=@item.name%></h3>

<%= render 'display_list' %>

<% if has_history?(@item) %>
  <%= link_to 'Revise', url_for(:action=>'revise', :id=>@item) %> |
<% end %>
<%= link_to 'Learn all', url_for(:action=>'learn', :id=>@item, :page=>0) %>
<br/><br/>
<% if can_edit?(@item) %>
  <%= link_to 'Edit', edit_ul_path(@item) %> |
<% end %>
<%= link_to 'Back', :root %>

app/views/uls/spottest_results.html.erb
<%
@right = @results[:right]
@extra = @results[:wrong]
@missed = @data.select{|item| @results[:right].select{|other| @item.soft_equal(other, item) }.length == 0}
%>

<h3><%=@right.length%> out of <%=@data.length%>:</h3>

<%= render 'results_display' %>

<%= link_to 'Try these again', @retry_url %>
| 
<%= link_to 'Move on', @progress_url %>
<br/>
<br/>
<%= link_to 'Back to menu', :root %>

app/views/uls/test.html.erb
<h3>Show me what you know:</h3>

<%=form_for(:ans, :url => @post_url, :method => :put) do |fo|%>
  <ul>
    <% first = true %>
    <% @data.each_index do |index| %>
      <% 
      options = {:autocomplete => 'off'} 
      if first then options[:autofocus] = 'autofocus' end
    %>
      <li><%=fo.text_field index, options%></li>
      <% first = false %>
    <%end%>
  </ul>
  <%= fo.submit 'I\'m done.', class: "btn" %>
<%end%>

<br/>

<%= link_to 'Back', :root %>