config/routes.rb
Didact::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :ols, :path => '/o', :except=>:destroy
  
  match 'o/:id/learn/:page' => 'ols#quiz', :via => :put
  match 'o/:id/learn/:page' => 'ols#learn', :via => :get
  match 'o/:id/testall' => 'ols#testall', :via => :get
  match 'o/:id/quizall' => 'ols#quizall', :via => :put
  match 'o/:id/improve' => 'ols#improve', :via => :get
  match 'o/:id/revise' => 'ols#revise', :via => :get
  match 'o/:id/quizimprove' => 'ols#quizimprove', :via => :put

  resources :uls, :path => '/u', :except=>:destroy
    
  match 'u/:id/learn/:page' => 'uls#quiz', :via => :put
  match 'u/:id/learn/:page' => 'uls#learn', :via => :get
  match 'u/:id/testall' => 'uls#testall', :via => :get
  match 'u/:id/quizall' => 'uls#quizall', :via => :put
  match 'u/:id/improve' => 'uls#improve', :via => :get
  match 'u/:id/revise' => 'uls#revise', :via => :get
  match 'u/:id/quizimprove' => 'uls#quizimprove', :via => :put
  
  resources :t2ts, :path => '/tt', :except=>:destroy
    
  match 'tt/:id/learn/:page' => 't2ts#quiz', :via => :put
  match 'tt/:id/learn/:page' => 't2ts#learn', :via => :get
  match 'tt/:id/testall' => 't2ts#testall', :via => :get
  match 'tt/:id/quizall' => 't2ts#quizall', :via => :put
  match 'tt/:id/improve' => 't2ts#improve', :via => :get
  match 'tt/:id/revise' => 't2ts#revise', :via => :get
  match 'tt/:id/quizimprove' => 't2ts#quizimprove', :via => :put
  
  resources :i2ts, :path => '/it', :except=>:destroy
    
  match 'it/:id/learn/:page' => 'i2ts#quiz', :via => :put
  match 'it/:id/learn/:page' => 'i2ts#learn', :via => :get
  match 'it/:id/testall' => 'i2ts#testall', :via => :get
  match 'it/:id/quizall' => 'i2ts#quizall', :via => :put
  match 'it/:id/improve' => 'i2ts#improve', :via => :get
  match 'it/:id/revise' => 'i2ts#revise', :via => :get
  match 'it/:id/quizimprove' => 'i2ts#quizimprove', :via => :put
  
  root :to => 'home#index'
  

end

app/models/ol.rb
require 'quiz'

class Ol < Quiz
  validates_presence_of :items
  validates_length_of :items, :within => 2..1000
  
  private
  field :items, :type => Array  
  
  public
  def mark (attempt)
    right = Hash.new
    wrong = Hash.new

    if !!attempt
      attempt.delete_if { |key,value| not key.to_i.between?(1, items.length) }
    
      attempt.keys.each do |key|
        attempt[key].strip!
        
        if soft_equal(attempt[key], items[key.to_i - 1])
          right[key] = attempt[key].to_s[0..200]
        else
          wrong[key] = attempt[key].to_s[0..200]
        end
      end
    end
    
    {right: right, wrong: wrong}
  end
  
  def get_data(min_value, max_value)
    data = Hash.new
    min_value.upto(max_value) do |number|
      data[(number + 1).to_s] = items[number]
    end
    
    return data
  end
end

app/controllers/ols_controller.rb
class OlsController < QuizController
  def initialize
    super('Ol')
  end
  
  def item_update(item, updateParams)
    if(not updateParams[:ol].nil?)
      item.update_attributes(updateParams[:ol])
            
      if(not updateParams[:ol][:items].nil?)
        vals = updateParams[:ol][:items].to_s.split("\n")
        vals.each { |x| x.strip! }
        vals.delete_if { |val| val.length == 0 }
        item.items = vals
      end
    end
  end
  
  def get_improvement_data
    ret = current_user.get_last_imperfect_go(@item)
    
    if ret[:wrong].length == 0 
      then 
      @item.get_all_data 
    else 
      @item.get_all_data
      @item.get_all_data.select{|key, value| ret.wrong.has_key?(key)} 
    end
  end
end

app/views/ols/_display_list.erb
<% if not @data.nil? %>
  <ol>
    <% @data.keys.each do |key| %>
      <li value="<%=key%>"><%=@data[key]%></li>
    <%end%>
  </ol>
<%end%>

app/views/ols/_edit_form.erb
<%= form_for(@item) do |f| %>
  <% if (not @item.errors.nil?) and @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> stopped us saving:</h2>

      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, 'Name:' %>
  <%= f.text_field :name %>

  <br/>
  <br/>
  Items:<br/>
  <% initialValue = if @data.nil? or @data.values.length == 0 then "Item 1\nItem 2\nItem 3" else @data.values.join("\n") end%>
  <%= f.text_area :items, :size => '30x10', :value=> initialValue%>

  <div class="actions">
    <%= f.submit 'Update!', class: "btn"%>
  </div>
<% end %>

app/views/ols/_results_display.erb
<%if not @right.empty?%>
  You <span style="color:#080; font-weight:bold;">aced</span> these:
  <ol>
    <% @right.keys.each do |index| %>
      <li value="<%=index%>"><%=@right[index]%></li>
    <%end%>
  </ol>
<%end%>

<%if not @wrong.empty?%>
  <span style="color:#800; font-weight:bold;">Not so hot</span> on these:
  <ol>
    <% @wrong.keys.each do |index| %>
      <li value="<%=index%>"><%=@data[index]%> 
        <% guess = @wrong[index].to_s%>
        <% if (not guess.nil?) and (not guess.empty?) %>
          (not "<%=guess%>")
        <%end%>
      </li>
    <%end%>
  </ol>
<%end%>

app/views/ols/display.html.erb
<H3>OK, now learn these <%=@item.name%>:</H3>

<%= render "display_list" %>

<%= link_to 'Test me!', @test_url%>

<br/>
<br/>

<%= link_to 'Back to menu', :root %>

app/views/ols/edit.html.erb
<h3>Editing <%=@item.name%></h3>

<%= render 'edit_form' %>

<%= link_to 'Show ' + @item.name, @item %>
<br/>
<br/>
<%= link_to 'Back to menu', :root %>

app/views/ols/full_results.html.erb
<%
@right = @results[:right].select { |key,value| @data.has_key?(key) }
@wrong = @results[:wrong].select { |key,value| @data.has_key?(key) }
%>

<h3><%=@right.length%> out of <%=@right.length + @wrong.length%>:</h3>

<%= render "results_display" %>

<%= link_to 'Try these again', url_for(:action => :testall) %> |
<%= link_to 'Back to ' + @item.name, url_for(:action => :show) %>

<br/>
<br/>
<%= link_to 'Back to menu', :root %>

app/views/ols/improve_results.html.erb
<%
@right = @results[:right]
@wrong = @results[:wrong].select { |key,value| @data.has_key?(key) }
%>

<h3><%=@right.length%> out of <%=@right.length + @wrong.length%>:</h3>

<%= render "results_display" %>

<%= link_to 'Try these again', url_for(:action => :improve) %> |
<%= link_to 'Back to ' + @item.name, url_for(:action => :show) %>

<br/>
<br/>
<%= link_to 'Back to menu', :root %>

app/views/ols/index.html.erb
<h1>All available ordered Pogos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @items.each do |ol| %>
    <tr>
      <td><span style="font-size:2em"><%=ol.name%></span> <br/>
        <%= link_to 'Show', ol %>
        | <%= link_to 'Learn all', url_for(:controller => 'ols', :action => 'learn', :id => ol, :page => 0) %>
        | <%= link_to 'Quiz all', url_for(:action=>'testall', :id => ol) %>
        | <%= link_or_text(has_history?(ol), 'Revise', url_for(:action=>'revise', :id=>ol), 'Log in to revise pogos you\'ve tried before') %>
        <% if can_edit?(ol) %>
          | <%= link_to 'Edit', edit_ol_path(ol) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<br />

<%= link_or_text(can_create?, 'Create new ordered Pogo', new_ol_path, 'Log in to create pogos') %>

app/views/ols/new.html.erb
<h1>New ordered Pogo</h1>

<%= render 'edit_form' %>

<%= link_to 'Back', :root %>

app/views/ols/show.html.erb
<h3><%=@item.name%></h3>

<%= render 'display_list' %>

<% if has_history?(@item) %>
  <%= link_to 'Revise', url_for(:action=>'revise', :id=>@item) %> |
<% end %>
<%= link_to 'Learn all', url_for(:action=>'learn', :id=>@item, :page=>0) %>
<br/><br/>
<% if can_edit?(@item) %>
  <%= link_to 'Edit', edit_ol_path(@item) %> |
<% end %>
<%= link_to 'Back to menu', :root %>

app/views/ols/spottest_results.html.erb
<%
@right = @results[:right].select { |key,value| @data.has_key?(key) }
@wrong = @results[:wrong].select { |key,value| @data.has_key?(key) }
%>

<h3><%=@right.length%> out of <%=@right.length + @wrong.length%>:</h3>

<%= render "results_display" %>

<%= link_to 'Try these again', @retry_url %>
<% if not @progress_url.nil? %>
  | <%= link_to 'Move on', @progress_url %>
<%end%>

<br/>
<br/>
<%= link_to 'Back to menu', :root %>

app/views/ols/test.html.erb
<h3>Show me what you know:</h3>

<%=form_for(:ans, :url => @post_url, :method => :put) do |fo|%>
  <ol>
    <% first = true %>
    <% @data.keys.each do |key| %>
      <% 
      options = {:autocomplete => 'off'} 
      if first then options[:autofocus] = 'autofocus' end
    %>
      <li value="<%=key%>"><%=fo.text_field key.to_s, options%></li>
      <% first = false %>
    <%end%>
  </ol>
  <%= fo.submit 'I\'m done.', class: "btn" %>
<%end%>

<br/>

<%= link_to 'Back to menu', :root %>